//! Bakes the C2PA signing credentials into the engine.
//!
//! The certificate chain and private key come from `C2PA_SIGNING_CERT` and
//! `C2PA_SIGNING_KEY` when both are set, and from `signing/` in the repository
//! root otherwise. The deploy workflow populates the environment from GitHub
//! secrets; CI and local builds fall through to the committed demo key so that
//! a fresh clone builds and signs without any setup.
//!
//! To be clear about what that buys: a secret keeps a key out of public git
//! history, and nothing more. This engine is compiled to WebAssembly and served
//! to browsers, so whichever key it holds is published the moment the site is.
//! `signing/README.md` covers why that is a property of client-side signing
//! rather than a shortcut taken here, and what a trustworthy setup looks like.

use std::env;
use std::fs;
use std::path::PathBuf;

const CERT_VAR: &str = "C2PA_SIGNING_CERT";
const KEY_VAR: &str = "C2PA_SIGNING_KEY";

fn main() {
    println!("cargo:rerun-if-env-changed={CERT_VAR}");
    println!("cargo:rerun-if-env-changed={KEY_VAR}");

    let crate_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let repo_signing = crate_dir.join("../../signing");
    let cert_file = repo_signing.join("demo-signer.pem");
    let key_file = repo_signing.join("demo-signer.key");
    let root_file = repo_signing.join("demo-root-ca.pem");

    for path in [&cert_file, &key_file, &root_file] {
        println!("cargo:rerun-if-changed={}", path.display());
    }

    // Both or neither. Taking a certificate from the environment and a key from
    // disk would produce a signature that cannot be verified by the very
    // certificate shipped alongside it, and the failure would only surface in a
    // validator somewhere downstream.
    let from_env = match (env::var(CERT_VAR), env::var(KEY_VAR)) {
        (Ok(cert), Ok(key)) if !cert.trim().is_empty() && !key.trim().is_empty() => {
            Some((cert, key))
        }
        (Ok(cert), Err(_)) if !cert.trim().is_empty() => {
            panic!("{CERT_VAR} is set but {KEY_VAR} is not; set both or neither");
        }
        (Err(_), Ok(key)) if !key.trim().is_empty() => {
            panic!("{KEY_VAR} is set but {CERT_VAR} is not; set both or neither");
        }
        _ => None,
    };

    let (cert_chain, private_key, provenance) = match from_env {
        Some((cert, key)) => (cert, key, "environment"),
        None => (
            read(&cert_file, CERT_VAR),
            read(&key_file, KEY_VAR),
            "repository",
        ),
    };

    // The trust anchor is never part of x5chain - it is read only so the app can
    // name the issuer. Missing is not fatal; the UI simply shows less.
    let root_ca = fs::read_to_string(&root_file).unwrap_or_default();

    let generated = format!(
        "// @generated by build.rs - do not edit.\n\
         /// PEM certificate chain, end-entity certificate first.\n\
         pub const SIGNING_CERT_CHAIN_PEM: &str = {cert};\n\
         /// PKCS#8 PEM private key matching the end-entity certificate.\n\
         pub const SIGNING_KEY_PEM: &str = {key};\n\
         /// The trust anchor that issued the signer. Not sent in x5chain.\n\
         pub const SIGNING_ROOT_CA_PEM: &str = {root};\n\
         /// Where the credentials came from at build time.\n\
         pub const SIGNING_CREDENTIAL_SOURCE: &str = {provenance:?};\n",
        cert = escape(&cert_chain),
        key = escape(&private_key),
        root = escape(&root_ca),
    );

    let out =
        PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR")).join("signing_credentials.rs");
    fs::write(&out, generated).unwrap_or_else(|e| panic!("writing {}: {e}", out.display()));
}

fn read(path: &PathBuf, var: &str) -> String {
    fs::read_to_string(path).unwrap_or_else(|e| {
        panic!(
            "could not read {} ({e}).\n\
             Either run signing/generate.sh to create the demo credentials, or \
             set {var} in the environment.",
            path.display()
        )
    })
}

/// Rust's own string escaping via `{:?}`. PEM is ASCII with newlines, so this
/// is exact rather than merely adequate.
fn escape(value: &str) -> String {
    format!("{value:?}")
}
